/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/LiceEse es el problema?nses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutable;

import AdministracionEmpleados.AdministracionController;
import AdministracionHabitacioness.Admin_Habitaciones;
import Interfaces.AdminHabitaciones;
// Digamos que tenia un grupo y los 2 se salieron de la U jajaaj

/**
 *
 * @author jprod
 */
public class frmMenuE extends javax.swing.JFrame {

    private AdministracionController controller;
    private AdminHabitaciones habitacioncontroller;

    /**
     * Creates new form FrmMenu
     */
    public frmMenuE() {
        initComponents();
        controller = new AdministracionController();
        habitacioncontroller = new Admin_Habitaciones();
    }

    public void setDesktopMenu(javax.swing.JDesktopPane desktopMenu) {
        AdministracionController controller = new AdministracionController();

        this.desktopMenu = desktopMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMenu = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        menuManage = new javax.swing.JMenu();
        MenuEmple = new javax.swing.JMenuItem();
        MenuHabi = new javax.swing.JMenuItem();
        MenuClient = new javax.swing.JMenuItem();
        service = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopMenuLayout = new javax.swing.GroupLayout(desktopMenu);
        desktopMenu.setLayout(desktopMenuLayout);
        desktopMenuLayout.setHorizontalGroup(
            desktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1005, Short.MAX_VALUE)
        );
        desktopMenuLayout.setVerticalGroup(
            desktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuManage.setText("Administrar");
        menuManage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuEmple.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuEmple.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icons/Miembros.png"))); // NOI18N
        MenuEmple.setText("Empleados");
        MenuEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpleActionPerformed(evt);
            }
        });
        menuManage.add(MenuEmple);

        MenuHabi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuHabi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuHabi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icons/Miembros.png"))); // NOI18N
        MenuHabi.setText("Habitaciones");
        MenuHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHabiActionPerformed(evt);
            }
        });
        menuManage.add(MenuHabi);

        MenuClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuClient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icons/Miembros.png"))); // NOI18N
        MenuClient.setText("Clientes");
        MenuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientActionPerformed(evt);
            }
        });
        menuManage.add(MenuClient);

        service.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        service.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icons/Miembros.png"))); // NOI18N
        service.setText("Servicios");
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        menuManage.add(service);

        menu.add(menuManage);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpleActionPerformed
        FrmEmpleados frmempleados = new FrmEmpleados(controller);
        desktopMenu.add(frmempleados);
        frmempleados.setVisible(true);
    }//GEN-LAST:event_MenuEmpleActionPerformed

    private void MenuHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHabiActionPerformed
        // TODO add your handling code here:
        FrmAdminHabitacion frm = new FrmAdminHabitacion(habitacioncontroller);
        desktopMenu.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MenuHabiActionPerformed

    private void MenuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientActionPerformed
        // TODO add your handling code here:
        FrmClientes frmclientes = new FrmClientes();
        desktopMenu.add(frmclientes);
        frmclientes.setVisible(true);
    }//GEN-LAST:event_MenuClientActionPerformed

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        FrmServicios frmServicios = new FrmServicios(); 
    desktopMenu.add(frmServicios); 
    frmServicios.setVisible(true);
    }//GEN-LAST:event_serviceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuClient;
    private javax.swing.JMenuItem MenuEmple;
    private javax.swing.JMenuItem MenuHabi;
    private javax.swing.JDesktopPane desktopMenu;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenuItem service;
    // End of variables declaration//GEN-END:variables
}
